spring.application.name=doodlemart-product

spring.config.import=optional:file:../.env[.properties]

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=${SUPABASE_DB_USER}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=doodlemart_product
spring.flyway.default-schema=doodlemart_product
spring.flyway.create-schemas=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=doodlemart_product

server.port=8081